apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests-back-app
spec:
  metrics:
    - name: integration-tests-back-app
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - name: integration-tests
                    image: integration-tests-image
                restartPolicy: Never
