apiVersion: v1
kind: Service
metadata:
  name: front-app
spec:
  selector:
    app: front-app
  ports:
    - name: http
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: back-app
spec:
  selector:
    app: back-app
  ports:
    - name: http
      port: 8081
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: front-app-preview
spec:
  selector:
    app: front-app-preview
  ports:
    - name: http
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: back-app-preview
spec:
  selector:
    app: back-app-preview
  ports:
    - name: http
      port: 8081
      targetPort: 5000