apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: python-demo-app

resources:
- ../../base

components:
  - ../../variants/prod

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
- rollout.yaml

images:
- name: integration-tests
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/dummy
- name: front-app
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app

