apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: python-demo-app

resources:
- ../../base

components:
- ../../variants/prod

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
- rollout.yaml

images:
- name: front-app-image
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app
- name: integration-tests-image
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/dummy

openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/main/schema/argo_all_k8s_kustomize_schema.json
