---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-app
spec:
  template:
    spec:
      containers:
        - name: front-app
          image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app