apiVersion: v1
kind: Service
metadata:
  name: front-app
spec:
  selector:
    app: front-app
  ports:
    - name: http
      port: 8080
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: front-app-canary
spec:
  selector:
    app: front-app-canary
  ports:
    - name: http
      port: 8080
      targetPort: 5000