
resources:
- service.yaml
- analysis_template.yaml
- rollout_front.yaml
- rollout_back.yaml
- namespace.yaml

images:
- name: integration-tests
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/dummy
- name: front-app
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app
- name: back-app
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/back-app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
