namespace: python-demo-app

resources:
- ../../base

components:
  - ../../variants/prod

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
- rollout.yaml

images:
- name: integration-tests
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/dummy
- name: back-app
  newName: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/back-app

