---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: back-app
spec:
  template:
    spec:
      containers:
        - name: back-app
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "grpc://simplest-collector.opentelemetry.svc.cluster.local:4317"
