apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
  labels:
    app: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: front-app
          image: front-app
          command: ["venv/bin/python", "-m", "flask", "--app", "front_app", "run", "-h", "0.0.0.0", "-p", "5000"]
          ports:
            - containerPort: 5000