apiVersion: v1
kind: Service
metadata:
  name: back-app
spec:
  selector:
    app: back-app
  ports:
    - name: http
      port: 8081
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: back-app-canary
spec:
  selector:
    app: back-app
    release: canary
  ports:
    - name: http
      port: 8080
      targetPort: 5000