---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: front-app
spec:
  template:
    spec:
      containers:
        - name: front-app
          env:
          - name: ENV
            value: "local"