apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlakewood

resources:
- ../../base

components:
  - ../../variants/local

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
