apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlakewood

resources:
- ../../base

components:
  - ../../variants/local

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml

openapi:
  path: https://github.com/argoproj/argo-schema-generator/raw/main/schema/argo_all_k8s_kustomize_schema.json