---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  template:
    spec:
      containers:
        - name: front-app
          image: 220445851985.dkr.ecr.ap-southeast-2.amazonaws.com/front-app